export const TOGGLE_NOTICE_DIALOG = 'TOGGLE_NOTICE_DIALOG';
export const NOTICE_LOAD_LIST = 'NOTICE_LOAD_LIST';

export const USER_DIALOG_TOGGLE = 'USER_DIALOG_TOGGLE';
export const USER_LIST_LOAD = 'USER_LIST_LOAD';
